[build]
  command = "yarn build"
  publish = "public"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"

[context.production.environment]
  HUGO_VERSION = "0.53"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"
